spigot:
  container_name: simplehub
  build: .
  volumes:
    - "/SimpleHub/spigot/world:/spigot/world"
    - "/SimpleHub/spigot/world_nether:/spigot/world_nether"
    - "/SimpleHub/spigot/world_the_end:/spigot/world_the_end"
    - "/SimpleHub/spigot/SimpleHub:/spigot/SimpleHub"
    - "/SimpleHub/spigot/SimpleHub_nether:/spigot/SimpleHub_nether"
    - "/SimpleHub/spigot/SimpleHub_the_end:/spigot/SimpleHub_the_end"
  ports:
    - "25566:25566"
  environment:
    - SIMPLEHUB_ENV=development
